spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/secure_payment_db
    username: secure_user
    password: secure_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: localhost
    port: 6379
    timeout: 6000
  session:
    store-type: redis
    timeout: 1800s

jwt:
  secret-key: "jK39Klj293sDfQWMe21nJe0f2/7gKa4r/c3Lu1sXh+I="
  validity-in-ms: 3600000

toss:
  api-url: https://api.tosspayments.com
  secret-key: test_sk_v2nJEeQvXGR2a0aWJg23PmOoBNO

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  error:
    whitelabel:
      enabled: false
    path: /error
