spring:
  security:
    enabled: false

  redis:
    host: localhost
    port: 6379
    timeout: 6000

  session:
    store-type: redis
    timeout: 1800s

toss:
  api-url: https://api.tosspayments.com/v1/payments
  secret-key: test_sk_v2nJEeQvXGR2a0aWJg23PmOoBNO

logging:
  level:
    root: INFO
    com.domain.payment: DEBUG

server:
  error:
    whitelabel:
      enabled: false
